FROM registry.access.redhat.com/ubi9/go-toolset@sha256:6f0e6c534d6b785530f7961089f444bbb14d384bfa3ea09070f5a70029b4a5cb as builder

ARG TARGETARCH
USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION 3.206.0
ENV PULUMI_BASE_URL="https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}"
ENV PULUMI_URL="${PULUMI_BASE_URL}-linux-x64.tar.gz"

RUN GOARCH=${TARGETARCH} make build \
    && if [ "$TARGETARCH" = "arm64" ]; then export PULUMI_URL="${PULUMI_BASE_URL}-linux-arm64.tar.gz"; fi \
    && echo ${PULUMI_URL} \
    && curl -L ${PULUMI_URL} -o pulumicli.tar.gz \
    && tar -xzvf pulumicli.tar.gz 

FROM quay.io/almalinuxorg/9-base@sha256:e32b7377ed7a9e3ffc8f53f230bf7285da3737445b0021eb46f0a2136a999a91

ARG TARGETARCH

LABEL org.opencontainers.image.authors="Redhat Developer"

COPY --from=builder /workspace/out/cloud-importer /workspace/pulumi/pulumi /usr/local/bin/
COPY --from=builder /workspace/oci/.aws/config /root/.aws/config

ENV PULUMI_CONFIG_PASSPHRASE "passphrase"

ENV AWS_CLI_VERSION=2.16.7 \
    ARCH_N=x86_64

# Pulumi plugins
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v7.11.0
# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v1.1.3
# renovate: datasource=github-releases depName=pulumi/pulumi-aws-native
ARG PULUMI_AWS_NATIVE_VERSION=v1.37.0
# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v3.10.1

ENV PULUMI_HOME "/opt/cloud-importer/run"
WORKDIR ${PULUMI_HOME}

ENV AZCOPY_URL https://aka.ms/downloadazcopy-v10-linux

RUN dnf install -y python3 python3-pip zstd qemu-img && \
    mkdir -p /opt/cloud-importer/run && \
    if [ "$TARGETARCH" = "arm64" ]; then export ARCH_N=aarch64; fi && \
    export AWS_CLI_URL="https://awscli.amazonaws.com/awscli-exe-linux-${ARCH_N}-${AWS_CLI_VERSION}.zip" && \
    curl ${AWS_CLI_URL} -o awscliv2.zip && \
    dnf install -y unzip && \
    unzip -qq awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip && \
    if [ "$TARGETARCH" = "arm64" ]; then export AZCOPY_URL="${AZCOPY_URL}-arm64"; fi && \
    curl -sSL ${AZCOPY_URL} | tar -xz -C /usr/local/bin --strip-components=1 --wildcards '*/azcopy' && \
    chmod +x /usr/local/bin/azcopy && \
    dnf clean all && \
  	rm -rf /var/cache/yum && \
    pulumi plugin install resource aws ${PULUMI_AWS_VERSION} && \
    pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} && \
    pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION} && \
    pulumi plugin install resource aws-native ${PULUMI_AWS_NATIVE_VERSION} && \
    chown -R 1001:0 /opt/cloud-importer/run && \
    chmod -R ug+rwx /opt/cloud-importer/run

USER 1001

ENTRYPOINT ["cloud-importer"]
CMD ["-h"]

