# Moved to Fedora 41 and install go tools until ubi9 go tools support go 1.23
FROM quay.io/fedora/fedora@sha256:e99eaeb7ad0008cb6278b38e8fdfb2715b6391e52a9fa88474f289410bf6ae67 as builder
RUN dnf install -y make go

ARG TARGETARCH
USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION 3.152.0
ENV PULUMI_BASE_URL="https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}"
ENV PULUMI_URL="${PULUMI_BASE_URL}-linux-x64.tar.gz"

RUN GOARCH=${TARGETARCH} make build \
    && if [ "$TARGETARCH" = "arm64" ]; then export PULUMI_URL="${PULUMI_BASE_URL}-linux-arm64.tar.gz"; fi \
    && echo ${PULUMI_URL} \
    && curl -L ${PULUMI_URL} -o pulumicli.tar.gz \
    && tar -xzvf pulumicli.tar.gz 

FROM quay.io/fedora/fedora@sha256:e99eaeb7ad0008cb6278b38e8fdfb2715b6391e52a9fa88474f289410bf6ae67 
ARG TARGETARCH
LABEL org.opencontainers.image.authors="Redhat Developer"

COPY --from=builder /workspace/out/cloud-importer /workspace/pulumi/pulumi /usr/local/bin/
COPY --from=builder /workspace/oci/.aws/config /root/.aws/config

ENV PULUMI_CONFIG_PASSPHRASE "passphrase" 

ENV AWS_CLI_VERSION=2.16.7 \
    ARCH_N=x86_64

# Pulumi plugins
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v6.70.0
# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v1.0.2
# renovate: datasource=github-releases depName=pulumi/pulumi-aws-native
ARG PULUMI_AWS_NATIVE_VERSION=v1.25.0

ENV PULUMI_HOME "/opt/cloud-importer/run" 
WORKDIR ${PULUMI_HOME}

RUN dnf install -y python3 python3-pip zstd qemu-img \
    && mkdir -p /opt/cloud-importer/run \
    && chmod -R 0777 /opt/cloud-importer/run \
    && if [ "$TARGETARCH" = "arm64" ]; then export ARCH_N=aarch64; fi \
    && export AWS_CLI_URL="https://awscli.amazonaws.com/awscli-exe-linux-${ARCH_N}-${AWS_CLI_VERSION}.zip" \
    && curl ${AWS_CLI_URL} -o awscliv2.zip \
    && dnf install -y unzip \
    && unzip -qq awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip \
    && dnf clean all \
  	&& rm -rf /var/cache/yum \
    && pulumi plugin install resource aws ${PULUMI_AWS_VERSION} \
    && pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} \
    && pulumi plugin install resource aws-native ${PULUMI_AWS_NATIVE_VERSION} 
    
ENTRYPOINT ["cloud-importer"]
CMD ["-h"]

